// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDB173VGfHjKhr6llPp7_bTwT7Y0RCK2ps',
    appId: '1:58972133285:web:b3494a16a2daf816763a4c',
    messagingSenderId: '58972133285',
    projectId: 'lunchnowapp',
    authDomain: 'lunchnowapp.firebaseapp.com',
    storageBucket: 'lunchnowapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeyadaHqsEKKf9PPcje6qJgRlZQIMDv3w',
    appId: '1:58972133285:android:0db235822613a00f763a4c',
    messagingSenderId: '58972133285',
    projectId: 'lunchnowapp',
    storageBucket: 'lunchnowapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcvsJDH6fwNLrWlJAuu4n9E4Ss_6BxHlI',
    appId: '1:58972133285:ios:7e1432ce872f1980763a4c',
    messagingSenderId: '58972133285',
    projectId: 'lunchnowapp',
    storageBucket: 'lunchnowapp.appspot.com',
    androidClientId: '58972133285-kbp3ek9ljkapeqkr0p14ocihpsi23u31.apps.googleusercontent.com',
    iosClientId: '58972133285-flmf86vlmi9h94ket1l9pa0epc47g0nh.apps.googleusercontent.com',
    iosBundleId: 'com.example.lunchNow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcvsJDH6fwNLrWlJAuu4n9E4Ss_6BxHlI',
    appId: '1:58972133285:ios:7e1432ce872f1980763a4c',
    messagingSenderId: '58972133285',
    projectId: 'lunchnowapp',
    storageBucket: 'lunchnowapp.appspot.com',
    androidClientId: '58972133285-kbp3ek9ljkapeqkr0p14ocihpsi23u31.apps.googleusercontent.com',
    iosClientId: '58972133285-flmf86vlmi9h94ket1l9pa0epc47g0nh.apps.googleusercontent.com',
    iosBundleId: 'com.example.lunchNow',
  );
}
